#!/usr/bin/env ruby
require 'tex'

# create multiple anki cards
def main(filepaths, outpath)
  parsed_objs = filepaths.map { |filepath| parse_tex(filepath) }
  parsed_objs = parsed_objs.select { |parsed_obj| !parsed_obj.nil? }
  anki_strs = parsed_objs.map { |parsed_obj| tex_to_anki(parsed_obj) }
  rv = save_anki_file(anki_strs, outpath)
end

# @todo update CLI to getoptlong
if $0 == __FILE__
  outpath = ARGV[0]
  filepaths = ARGV[1..-1]
  rv = main(filepaths, outpath)
end
